import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  skill: [
    'skill/introduction',
    {
      label: 'Python',
      type: 'category',
      link: {
        // title: '',
        // description: '',
        type: 'generated-index',
        keywords: ['Django',],
      },
      items: [
        {
          label: 'Django',
          type: 'category',
          link: {
            type: 'doc',
            id: 'skill/python/Django/django-orm-ForeignKey-on_delete',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/python/Django',
            },
          ],
        },
      ],
    },
    {
      label: 'Vue',
      type: 'category',
      link: {
        // title: '',
        // description: '',
        type: 'generated-index',
        keywords: ['Vue', 'FastCrud',],
      },
      items: [
        {
          label: 'FastCrud',
          type: 'category',
          link: {
            type: 'doc',
            id: 'skill/vue/FastCrud/fast-crud',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/vue/FastCrud',
            },
          ],
        },
      ],
    },
    {
      label: '数据库DB',
      type: 'category',
      link: {
        // title: '',
        // description: '',
        type: 'generated-index',
        keywords: ['database', 'mysql', 'mongodb', 'redis', 'elasticsearch', 'postgresql'],
      },
      items: [
        {
          label: 'PostgreSQL',
          type: 'category',
          link: {
            type: 'doc',
            id: 'skill/db/PostgreSQL/postgresql-common-commands',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'skill/db/PostgreSQL',
            },
          ],
        },
      ],
    },
    {
      label: 'Docker',
      type: 'category',
      link: { type: 'generated-index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/docker',
        },
      ],
    },
    {
      label: 'Mac',
      type: 'category',
      link: { type: 'generated-index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'skill/mac',
        },
      ],
    },
    
  ],
}

module.exports = sidebars
